# Generated by Django 6.0.4 on 2026-05-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mad_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
