# Generated by Django 6.0.4 on 2026-05-05 16:05

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mad_user', '0003_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatars/default.jpg', force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[300, 300], upload_to='avatars/'),
        ),
    ]
