# Generated by Django 6.0.4 on 2026-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_user', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
